version: "3.0"

services:
  qix-engine:
    image: qlikcore/engine:12.925.0
    command: -S AcceptEULA=${ACCEPT_EULA} -S TrafficLogVerbosity=5 -S SystemLogVerbosity=5
    ports:
      - 19076:9076
      - 9090:9090
    labels:
      qix-engine: ""
