version: "3.0"

services:

  qix-engine:
    image: qlikcore/engine:12.171.0
    deploy:
      replicas: 2
    command: -S AcceptEULA=${ACCEPT_EULA} -S LicenseServiceUrl=http://licenses:9200 -S DisableStartupLicenseCheck=1 -S TrafficLogVerbosity=5 -S SystemLogVerbosity=5
    ports:
      - 19076:9076
      - 9090:9090
    labels:
      qix-engine: ""

  licenses:
    image: qlikcore/licenses:experimental
    environment:
      - LICENSES_SERIAL_NBR
      - LICENSES_CONTROL_NBR
      - LICENSES_LOG_LEVEL=debug
    ports:
      - 9200:9200
