version: "3.0"

services:
  prometheus:
    image: prom/prometheus:v2.25.1
    command: '--config.file=/etc/prometheus/config.yml'
    volumes:
      - ./configs/prometheus/config.yml:/etc/prometheus/config.yml
  grafana:
    image: grafana/grafana:5.4.5
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: 'Admin'
    volumes:
      - ./configs/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./configs/grafana/dashboards:/etc/grafana/provisioning/dashboards
