
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/qlik-oss/core-using-licenses
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run:
          name: Install toolchain
          command: |
            go get -u github.com/golang/dep/cmd/dep
            go get -u github.com/golang/lint/golint
      - restore_cache:
          key: dependency-cache-{{ checksum "Gopkg.lock" }}
      - run:
          name: Install dependencies
          command: dep ensure
      - save_cache:
          key: dependency-cache-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - run:
          name: Linting
          command: golint -set_exit_status
      - setup_remote_docker
      - run:
          name: Run tests without license
          command: |
            ACCEPT_EULA=yes docker-compose -f docker-compose.only-engine.yml up -d
            sleep 10 # How should we handle this?
            CONTAINER_ID=$(docker ps -aqf "name=core-using-licenses_qix-engine_1")
            TEST_HOST=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.Gateway}}{{end}}' "$CONTAINER_ID")
            echo $TEST_HOST
            go test -timeout 30s test/no_license_test.go test/utils_test.go
            docker-compose -f docker-compose.only-engine.yml down