
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/qlik-oss/core-using-licenses
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run:
          name: Install toolchain
          command: |
            go get -u github.com/golang/dep/cmd/dep
            go get -u github.com/golang/lint/golint
      - restore_cache:
          key: dependency-cache-{{ checksum "Gopkg.lock" }}
      - run:
          name: Install dependencies
          command: dep ensure
      - save_cache:
          key: dependency-cache-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - run:
          name: Linting
          command: golint -set_exit_status
      - setup_remote_docker
      - run:
          name: Run tests without license
          command: |
            # Spin up environment
            ACCEPT_EULA=yes docker-compose -f docker-compose.only-engine.yml up -d
            CONTAINER_ID=$(docker ps -aqf "name=core-using-licenses_qix-engine_1")
            TEST_HOST=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.Gateway}}{{end}}' "$CONTAINER_ID")

            # Start a container for test execution
            TEST_CONTAINER=$(docker run -e TEST_HOST=$TEST_HOST -d golang:1.9-alpine tail -f /dev/null)
            # Copy code into container
            docker cp /go/src/github.com/qlik-oss/core-using-licenses/ $TEST_CONTAINER:/go/src/license_test/
            # Execute tests
            docker exec $TEST_CONTAINER sh -c 'go test -timeout 30s /go/src/license_test/test/no_license_test.go /go/src/license_test/test/utils_test.go'
            # Bring down the docker-compose and test container
            docker-compose -f docker-compose.only-engine.yml down
            docker kill $TEST_CONTAINER
      - run:
          name: Run tests with license
          command: |
            # Spin up environment
            ACCEPT_EULA=yes docker-compose -f docker-compose.engine-and-license-service.yml up -d
            CONTAINER_ID=$(docker ps -aqf "name=core-using-licenses_qix-engine_1")
            TEST_HOST=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.Gateway}}{{end}}' "$CONTAINER_ID")

            # Start a container for test execution
            TEST_CONTAINER=$(docker run -e TEST_HOST=$TEST_HOST -d golang:1.9-alpine tail -f /dev/null)
            # Copy code into container
            docker cp /go/src/github.com/qlik-oss/core-using-licenses/ $TEST_CONTAINER:/go/src/license_test/
            # Execute tests
            docker exec $TEST_CONTAINER sh -c 'go test -timeout 30s /go/src/license_test/test/with_license_test.go /go/src/license_test/test/utils_test.go'
            # Bring down the docker-compose
            docker-compose -f docker-compose.engine-and-license-service.yml down
            docker kill $TEST_CONTAINER