global:
  scrape_interval: 1s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'qix-engine'
    static_configs:
      - targets: ['qix-engine:9090']
  - job_name: 'licenses'
    static_configs:
      - targets: ['licenses:9200']
